In [2]:
import numpy as np 
np.__version__

'1.26.4'

In [4]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))

In [5]:
print(arr1)
print(arr2)
type(arr1)
type(arr2)

[1 3 5 7 9]
[1 3 5 7 9]


numpy.ndarray

#### 1.2 Creating array by numpy.arrage() function

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,30,4)

array([ 2,  6, 10, 14, 18, 22, 26])

In [10]:
np.array(['name','address','discount'])

array(['name', 'address', 'discount'], dtype='<U8')

In [16]:
np.linspace(0,1,num = 10,endpoint=False,retstep=True,axis=0)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]), 0.1)

In [18]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
arr1 = np.linspace(0,1,5,endpoint=True  )
print(type(arr1))

<class 'numpy.ndarray'>


In [23]:
arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [24]:
print(arr[0])

[ 0.   2.5  5.   7.5 10. ]


In [25]:
arr[1]

2.5

In [27]:
arr2d = np.zeros((10,10),dtype=float)

In [28]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
type(arr2d[0][0])

numpy.float64

In [30]:
arr2d_1 = np.array([[1,2],[3,4],[5,6],[7,8]])


In [32]:
arr2d_1


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
arr2d_1.ndim

2

In [36]:
arr2d_1.shape

(4, 2)

In [38]:
arr2d_1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 1.3 Indexing and slicing NumPy arrays:¶

In [39]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
b= np.append(a,[[11,22,33]],axis= 0)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33]])

In [44]:
c= np.append(a,[[11],[22],[33]],axis= 1)
c

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 33]])

In [47]:
d =c[:2]
d

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 22]])

In [48]:
c[1:,1:]

array([[ 5,  6, 22],
       [ 8,  9, 33]])

In [58]:
arr =np.arange(100)
arrMask = ((arr%5) == 1) &( arr >51)
arr[arrMask]

array([56, 61, 66, 71, 76, 81, 86, 91, 96])

#### 1.4. NumPy attributes and reshaping:


In [60]:
a = np.arange(20)
a.reshape(4,5)
#### reshape end : just to view not change in the martix A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
# to make a new object i think  you should use reshape and copy togerther to make it 
c= a.reshape(10,2).copy()
a[0,0] = 10

c
# before change you will see if you change the elements in a then c was only changed

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [72]:
# after  change you will see if you add copy function in the code  the elements in c not dependency of a 
c[0,0] = 10
c

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [73]:
c.reshape(5,4).copy()


array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### 1.5. Modifying NumPy arrays:

In [74]:
a= np.array([1,2,3])
b =np.append(a,[4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [75]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [77]:
np.delete(a,(0,2,4))

array([2, 4, 6])

In [79]:
np.delete(a,0,axis=0)

array([[4, 5, 6]])

In [81]:
np.delete(a,0,axis=1)

array([[2, 3],
       [5, 6]])