In [2]:
import numpy as np

### 1. NumPy array operations:

#### 1.1. '+' and '*' and '/' operators for Python lists:

In [2]:
# In list operator plus is used to connect two lists
# In numpy + is used to math operations
a = [1,2,3]
a+a

[1, 2, 3, 1, 2, 3]

In [10]:
arr = np.array([1,2,3])
arr2  = np.array([4,5,6])
arr+arr2

array([5, 7, 9])

In [7]:
arr*arr2

array([1, 4, 9])

In [11]:
print(arr-arr2)
print(arr*arr2)
print(arr/arr2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#### 1.2. Universal functions:

In [13]:
x = np.array([0, 1, 2, 3, 4, 5])
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [15]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [17]:
# Sum function and mean function
x= np.arange(1,11)
x.sum()

55

In [18]:
# mean function 
x.mean()

5.5

In [19]:
# The deviation of each element in the array."
x_mean = x.mean()
x -x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [20]:
# The square deviation  in the array."
(x -x_mean) **2


array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [22]:
# Sum of squared deviations
dev = (x - x_mean) **2
dev.sum()

82.5

In [27]:
# variance funtion 
# Two ways to calculate the vartiane ( Phuong sai)
print(dev.sum() / x.size)
print(x.var())


8.25
8.25


In [29]:
#standard deviation function
print(np.sqrt(x.var()))
print(x.std())

2.8722813232690143
2.8722813232690143


In [31]:
# cunsum function
print(x)
x.cumsum()

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [35]:
z = np.random.randint(10,size=1000)
z.max()

9

In [3]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
arr= np.random.randn(6,3)
arr

array([[-0.32758613,  0.37626744,  1.37118631],
       [-2.02240082,  0.36769326, -0.10632449],
       [ 0.06480896,  0.89449875, -0.03273737],
       [ 0.48913881, -0.989235  ,  1.91609867],
       [ 0.06325793,  1.93772672, -0.34287134],
       [-1.45688474,  1.19990084,  0.86922775]])

In [8]:
arr.T

array([[-0.32758613, -2.02240082,  0.06480896,  0.48913881,  0.06325793,
        -1.45688474],
       [ 0.37626744,  0.36769326,  0.89449875, -0.989235  ,  1.93772672,
         1.19990084],
       [ 1.37118631, -0.10632449, -0.03273737,  1.91609867, -0.34287134,
         0.86922775]])

#### 1.2. Dot martrix funtion

In [10]:
np.dot(arr.T,arr)

array([[ 6.56738942, -2.91832549, -0.5870883 ],
       [-2.91832549,  7.25003627, -1.06932129],
       [-0.5870883 , -1.06932129,  6.43708028]])

In [12]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [15]:
arr.transpose(2,0,1)

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [16]:
arr.transpose(0,1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])