In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])		# A one dimensional NumPy array.

In [5]:
a[:2]                  	# From the index 0 up to the index 1 (excluding 2).

array([1, 2])

In [7]:
a[2:]                   # From the index 2 up to the index 4 .

array([3, 4, 5])

In [9]:
a[-1]                    # value of last element

5

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])	# This is a 3 x 3 two dimensional array (matrix). 

In [12]:
a[1]				# The row 1.

array([4, 5, 6])

In [13]:
a[-1]				# The  last row .


array([7, 8, 9])

In [14]:
a[:]				# The whole array (matrix).

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[:2]				# From the row 0 to the row 1 (excluding the row 2).	

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[2][1]			# The element from the row 2 and the column 1.	

8

In [20]:
a[[0,2]]      # The rows 0 and 2 

array([[1, 2, 3],
       [7, 8, 9]])

In [22]:
a[1:, 1:]			# From the row 1 to the end. From the column 1 to the end.

array([[5, 6],
       [8, 9]])